version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "11:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: botkit
    versions:
    - "> 0.7.4"
  - dependency-name: airtable
    versions:
    - 0.10.1
  - dependency-name: moment-timezone
    versions:
    - 0.5.32
